Revenge Item done
JarrydWorland/2021_Capstone_GP2_Team pull request #188
Opened 2021-11-02 05:59 UTC by BasilChristofis

Sprite size changed to match the rest, box collider changed in size to compencsate difference. Revenge Item takes player damage, and allows a value equal to it be used to add damage to the bullet. Uses Weapon Damage sfx at the moment.

Please check by spawning the revenge item, taking damage once, dropping it, and picking it up again, to see if additional damage still remains.

Please also check by holding more than one revenge item at once, and ensuring additional damage is accurate for the number of items in the inventory.

2021-11-02 12:52 UTC, JarrydWorland commented
I think the implementation of the projectile size needs more than what it is. 

At the moment it's purely cosmetic and doesn't serve much purpose - perhaps these should be made to be invulnerable, except on wall collisions, where you could potentially have it affect two or three targets in a row without destroying on contact with an enemy?

2021-11-03 00:15 UTC, LachlanMcCaskill commented
For the projectile size item, we need to set it such that it changes how big the projectile gets each time, with diminishing returns. The first time it should be significant, but then it should be smaller every time after that. I'll see if I can implement this using a stack.

2021-11-03 00:28 UTC, LachlanMcCaskill commented
Update: I don't think it can be done using a stack, but I think it can be done by changing the value of addScale based on the current scale of the projectile (provided you already have access)

2021-11-03 03:41 UTC, 102107466 requested changes
Some things I think should be addressed.

2021-11-03 03:41 UTC, 102107466 commented on MicrowaveGame/Assets/Resources/Scenes/Gameplay.unity
> +      objectReference: {fileID: 0}
I don't think this was intentional but it looks like the aim assist cone angle has been set to 0 for the gameplay scene.

2021-11-03 03:41 UTC, 102107466 commented on MicrowaveGame/Assets/Resources/Prefabs/Projectiles/ProjectileBullet.prefab
> +      objectReference: {fileID: 0}
Not sure why this was changed but transform scale z should not be 0, I would leave it the same as the other values (0.1) or 1.0

2021-11-03 03:41 UTC, 102107466 commented on MicrowaveGame/Assets/Resources/Scripts/Player/PlayerShootBehaviour.cs
> +			_projectilePrefab.transform.localScale = new Vector3(0.1f, 0.1f, 0);
Again, z scale should not be 0.

2021-11-03 03:41 UTC, 102107466 commented on MicrowaveGame/Assets/Resources/Scripts/Items/ItemProjectileSizeBehaviour.cs
> +		private Vector3 AddScale = new Vector3(0.05f,0.05f,0);
private should be `_addScale`

2021-11-03 05:59 UTC, LachlanMcCaskill commented
The key problem with the projectile size right now is not in this implementation, it's the way the collisions work. We can't make the projectile significantly bigger without causing issues with collisions when the player tries to shoot while next to a wall. Rewriting the collision detection for shooting to accommodate this sounds like too much work, so I would recommend leaving this out and focusing on other remaining tasks.

2021-11-03 10:50 UTC, 102113528 approved these changes
I've lowered the increase size to be more reasonable with four items.

Seems alright otherwise :+1:

2021-11-03 10:52 UTC, merged